### ISSUE TITLE
[feature request] Don't sell shotguns, ammo, or gifts by default

### ISSUE THREAD

**Issue by a1russell** [riceisacereal/MinimumQuotaFinder#12]
Hi,

I love the idea of your mod. I would definitely use this if it were to, by default, exclude shotguns, ammo, and gifts from its calculations.

Have a great day!

**Comment by riceisacereal** [comment]
Thank you for the suggestion! We've just added this and uploaded v1.1.1, this will be a nice temporary fix before we figure out how to best implement more customizability with config files.
