### ISSUE TITLE
[potential noob question] why is the algorithm like that?

### ISSUE THREAD

**Issue by viiuan** [riceisacereal/MinimumQuotaFinder#15]
i started a new solo game recently and wanted to try out this mod since i like the wireframe shader a lot better than calculatescrapforquota's colour overlay. however i noticed that, at least in my first quota, it refused to highlight anything other than a cash register i had picked up even though its value was 12 over quota. i actually found out myself that i had a few different items that added up to exactly the quota value, which is what i prefer as selling over quota increases the next one slightly.
so; why would it do this? is it also meant to try and sell the minimum *number of scrap items* possible? can you change this, or offer it as a user choice?
for comparison, calculatescrapforquota seems to always try and get it as close to the exact quota value as possible, and personally i have never seen a point where it hasn't found a combo of scrap that meets quota exactly.
i honestly would love just for this wireframe shader to be used in calculatescrapforquota, if that is also something viable... but i know those are different projects with different authors. i'd try it myself but i have no idea how easy or difficult making LC mods is

SORRY FOR WORD VOMIT! i am autistic <3

**Comment by riceisacereal** [comment]
Interesting, the situation you encountered _shouldn't happen_ to say the least, so we probably missed something in our code or something else is going wrong. Currently our algortihm just tries to find the closest match possible, so if an exact match exists it should highlight that (and we haven't added a thing for preferring the least amount of items yet) and it looks through all possible combinations so it shouldn't miss a better combination. Both me and @Luesewr are currently in our finals week so we'll get back to you a bit later. Meanwhile it's been a while and I don't remember if it was possible to send save files in LC? Or if you can recreate the issue with certain combinations of scrap under specific conditions (such as first quota, on a moon/the company) you can describe that to us as well. It would be nice if we could recreate the issue on our end so we can try to see what's going wrong.

Also no worries for the word vomit, issue descriptions are more helpful the more detailed they are <3

**Comment by viiuan** [comment]
gotcha gotcha! in that case i can see about trying to recreate it, find a moon seed that has a cash register lol, otherwise maybe it was a fluke or something to do with my other mods...
i can say that it was doing that highlighting as soon as i got the cash register though. didnt matter if i was in orbit or on a moon

**Comment by riceisacereal** [comment]
Interesting, do you mean that you encountered it multiple times and every time it was only the cash register that triggered it? And by "as soon as i got" do you mean like picking up the cash register on a moon or taking it back to the ship? If I remember correctly, we should only have auto-calculation triggers when landing on the company. I'm gonna have to revisit our code again to remember the details though. While debugging an issue someone else faced, we did find that, probably due to the large amount of mods they had, that their auto-calculation was triggering constantly.

**Comment by viiuan** [comment]
oh nah, it's only happened once so far but i just found it so odd since you daid you used the same algorithm as calculatescrapforquota
auto-calc only happened on the company moon, i just mean when i manually highlighted AND when auto-calc happened it only highlighted the cash register lol

**Comment by riceisacereal** [comment]
Technically the type of scrap shouldn't matter unless it's a shotgun, ammo, or gift in which case it's completely excluded in the calculation (we still need to make this more customizable).

**Comment by viiuan** [comment]
similarly not correctly finding items to exactly meet quota, it calculated a set of items that was 1 over quota and after i sold a couple of easter eggs (i prefer to sell them first so they don't explode on me lol) it found a different combo that met quota exactly
the cash register is still part of the highlight lol. here's my save file https://files.catbox.moe/pzbewb
![image](https://github.com/riceisacereal/MinimumQuotaFinder/assets/63260365/bb4b28e4-b0dc-47d5-976b-db3a9e8a9e1e)
and these are my mods. could any of these interfere with this mod?

**Comment by viiuan** [comment]
i've switched back to calculatescrapforquota for now as this issue is continuing on new saves and with all sorts of different item combinations

**Comment by Luesewr** [comment]
We've looked into the problem, and we've found a disappointingly stupid bug within our direct target calculation. We'll get to fixing it as soon as possible. Thanks for the issue report!

**Comment by Luesewr** [comment]
We've fixed the issue we found and uploaded version 1.1.4. It should find an exact combination in the save file you uploaded now. The new version will be online on Thunderstore in a bit. Thanks again for reporting the issue, this was a pretty big blunder on our part. Hopefully it works as intended now.
