### ISSUE TITLE
Mesh disappears on certain scrap items from a distance

### ISSUE THREAD

**Issue by throwitaway99** [riceisacereal/MinimumQuotaFinder#6]
I've noticed that on specific scrap items (in this case, I've so far only noticed this on bottles), that the mesh will disappear past a certain distance. I have included a video to demonstrate this.

https://github.com/riceisacereal/MinimumQuotaFinder/assets/136512585/9b5e95cd-aa99-4c6a-994a-03335a42d1f4

Additionally, some clarification: is it intended behavior for shotguns to only have the mesh replace a part of the model, as opposed to being fully replaced by the mesh?

**Comment by Luesewr** [comment]
I have also noticed this for Tragedy Masks. This seems to happen because of the base game, our mod does not do anything with render distance, I will look into maybe patching this if I can find out where it happens. As for your second question, currently I am replacing all the materials of the mesh in the MeshRenderer, this however does not seem to replace the materials of the moving parts of objects, like the pins in D.I.Y. flashbangs, the handle on cash registers and the moving parts of shotguns probably among others. I will look into this more once I get some more time on my hands, probably tomorrow.

**Comment by Luesewr** [comment]
My guess is that the render distance issue has something to do with the LOD system in the game as Tragedy Masks and bottles have a high density of polygons compared to most other items. The game is likely replacing these high polygon-density objects with less detailed models at certain distances. Even if we can stop the game from replacing these objects with less detailed objects it might also come into question whether this is a good idea in the first place as the higher detailed objects might have an impact on the performance of the game.

**Comment by throwitaway99** [comment]
Can confirm, upon using a mod that raises the LOD, that I can go further without the mesh disappearing (a much more respectable distance). To be honest, I've felt that even the max LOD said mod offers is a bit conservative, though it's certainly an improvement. It certainly makes me wish there was more fine control over LOD for those with more powerful systems.

**Comment by Luesewr** [comment]
Could you link me the mod? I could look into their code and maybe try to add a feature that increased the LOD for highlighted objects, such that they're easier to find (on our mod that is)

**Comment by throwitaway99** [comment]
The mod is [HDLethalCompany](https://thunderstore.io/c/lethal-company/p/Sligili/HDLethalCompany/). The LOD can be changed via the config presets (2 is the max - double the vanilla LOD), which makes me wonder if it could be modified to support higher LOD for general use.

**Comment by Luesewr** [comment]
I have improved the way we replaced the materials of the objects and it now also replaces the materials of the MeshRenderers associated with the LODs, this new way of replacing the materials also fixed the bug where the moving parts of objects did not have their materials replaced.
